apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loan-platform

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secrets.yaml
  - persistent-volumes.yaml
  - api-gateway.yaml
  - workflow-service.yaml
  - services.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: ai-loan-governance-platform
