apiVersion: v1
kind: ServiceAccount
metadata:
  name: loan-platform-sa
  namespace: loan-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loan-platform-role
  namespace: loan-platform
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loan-platform-rb
  namespace: loan-platform
subjects:
  - kind: ServiceAccount
    name: loan-platform-sa
    namespace: loan-platform
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: loan-platform-role
